//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\Siemens\AutoInstaller\AutoInstaller\AISL\AISL.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AISLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IAISLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] AISLParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.findInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFindInstruction([NotNull] AISLParser.FindInstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.hasBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHasBlock([NotNull] AISLParser.HasBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] AISLParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] AISLParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.uninstallInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUninstallInstruction([NotNull] AISLParser.UninstallInstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.executeInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecuteInstruction([NotNull] AISLParser.ExecuteInstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.installerPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstallerPath([NotNull] AISLParser.InstallerPathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.programName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgramName([NotNull] AISLParser.ProgramNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.installationsPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstallationsPath([NotNull] AISLParser.InstallationsPathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.parameterType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterType([NotNull] AISLParser.ParameterTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.parameterName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterName([NotNull] AISLParser.ParameterNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.parameterDefaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDefaultValue([NotNull] AISLParser.ParameterDefaultValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.parameterFixedValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterFixedValue([NotNull] AISLParser.ParameterFixedValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.parameterIsOptional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterIsOptional([NotNull] AISLParser.ParameterIsOptionalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.optionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionList([NotNull] AISLParser.OptionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOption([NotNull] AISLParser.OptionContext context);
}
