//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\Siemens\AutoInstaller\AutoInstaller\AISL\AISL.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class AISLLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		FIND=1, AT=2, HAS=3, WITH=4, DEFAULT=5, AS=6, FROM=7, UNINSTALL=8, EXECUTE=9, 
		INSTALLATION_PARAMETERS=10, OPTIONAL=11, WORD=12, QUOTED_TEXT=13, SEMICOLON=14, 
		COMMA=15, OPEN_PARENTHESIS=16, CLOSE_PARENTHESIS=17, OPEN_SQUARE_BRACKET=18, 
		CLOSE_SQUARE_BRACKET=19, EQUALS=20, WHITESPACE=21, NEWLINE=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"LOWERCASE", "UPPERCASE", "DIGIT", "FIND", "AT", "HAS", "WITH", "DEFAULT", 
		"AS", "FROM", "UNINSTALL", "EXECUTE", "INSTALLATION_PARAMETERS", "OPTIONAL", 
		"WORD", "QUOTED_TEXT", "SEMICOLON", "COMMA", "OPEN_PARENTHESIS", "CLOSE_PARENTHESIS", 
		"OPEN_SQUARE_BRACKET", "CLOSE_SQUARE_BRACKET", "EQUALS", "WHITESPACE", 
		"NEWLINE"
	};


	public AISLLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public AISLLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, "'installation_parameters'", 
		"'optional'", null, null, "';'", "','", "'('", "')'", "'['", "']'", "'='"
	};
	private static readonly string[] _SymbolicNames = {
		null, "FIND", "AT", "HAS", "WITH", "DEFAULT", "AS", "FROM", "UNINSTALL", 
		"EXECUTE", "INSTALLATION_PARAMETERS", "OPTIONAL", "WORD", "QUOTED_TEXT", 
		"SEMICOLON", "COMMA", "OPEN_PARENTHESIS", "CLOSE_PARENTHESIS", "OPEN_SQUARE_BRACKET", 
		"CLOSE_SQUARE_BRACKET", "EQUALS", "WHITESPACE", "NEWLINE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "AISL.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static AISLLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x18', '\xF0', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '\x44', 
		'\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', 
		'\x6', 'J', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', 'R', '\n', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x5', '\b', '\\', '\n', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x5', '\t', 'l', '\n', '\t', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x5', '\n', 'r', '\n', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x5', '\v', '|', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x5', '\f', 
		'\x90', '\n', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', 
		'\xA0', '\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x6', '\x10', '\xC6', '\n', '\x10', '\r', 
		'\x10', '\xE', '\x10', '\xC7', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', 
		'\xCC', '\n', '\x11', '\f', '\x11', '\xE', '\x11', '\xCF', '\v', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x19', '\x6', '\x19', '\xE2', '\n', '\x19', '\r', 
		'\x19', '\xE', '\x19', '\xE3', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', 
		'\x5', '\x1A', '\xE9', '\n', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x6', 
		'\x1A', '\xED', '\n', '\x1A', '\r', '\x1A', '\xE', '\x1A', '\xEE', '\x3', 
		'\xCD', '\x2', '\x1B', '\x3', '\x2', '\x5', '\x2', '\a', '\x2', '\t', 
		'\x3', '\v', '\x4', '\r', '\x5', '\xF', '\x6', '\x11', '\a', '\x13', '\b', 
		'\x15', '\t', '\x17', '\n', '\x19', '\v', '\x1B', '\f', '\x1D', '\r', 
		'\x1F', '\xE', '!', '\xF', '#', '\x10', '%', '\x11', '\'', '\x12', ')', 
		'\x13', '+', '\x14', '-', '\x15', '/', '\x16', '\x31', '\x17', '\x33', 
		'\x18', '\x3', '\x2', '\x6', '\x3', '\x2', '\x63', '|', '\x3', '\x2', 
		'\x43', '\\', '\x3', '\x2', '\x32', ';', '\x4', '\x2', '\v', '\f', '\"', 
		'\"', '\x2', '\xFD', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x3', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\a', '\x39', '\x3', '\x2', '\x2', '\x2', '\t', '\x43', '\x3', '\x2', 
		'\x2', '\x2', '\v', 'I', '\x3', '\x2', '\x2', '\x2', '\r', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\xF', '[', '\x3', '\x2', '\x2', '\x2', '\x11', 'k', 
		'\x3', '\x2', '\x2', '\x2', '\x13', 'q', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'{', '\x3', '\x2', '\x2', '\x2', '\x17', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\x19', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x1B', '\xA1', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\xB9', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'\xC5', '\x3', '\x2', '\x2', '\x2', '!', '\xC9', '\x3', '\x2', '\x2', 
		'\x2', '#', '\xD2', '\x3', '\x2', '\x2', '\x2', '%', '\xD4', '\x3', '\x2', 
		'\x2', '\x2', '\'', '\xD6', '\x3', '\x2', '\x2', '\x2', ')', '\xD8', '\x3', 
		'\x2', '\x2', '\x2', '+', '\xDA', '\x3', '\x2', '\x2', '\x2', '-', '\xDC', 
		'\x3', '\x2', '\x2', '\x2', '/', '\xDE', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xE1', '\x3', '\x2', '\x2', '\x2', '\x33', '\xEC', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x36', '\t', '\x2', '\x2', '\x2', '\x36', '\x4', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\x38', '\t', '\x3', '\x2', '\x2', '\x38', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\t', '\x4', '\x2', '\x2', 
		':', '\b', '\x3', '\x2', '\x2', '\x2', ';', '<', '\a', 'H', '\x2', '\x2', 
		'<', '=', '\a', 'K', '\x2', '\x2', '=', '>', '\a', 'P', '\x2', '\x2', 
		'>', '\x44', '\a', '\x46', '\x2', '\x2', '?', '@', '\a', 'h', '\x2', '\x2', 
		'@', '\x41', '\a', 'k', '\x2', '\x2', '\x41', '\x42', '\a', 'p', '\x2', 
		'\x2', '\x42', '\x44', '\a', '\x66', '\x2', '\x2', '\x43', ';', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '?', '\x3', '\x2', '\x2', '\x2', '\x44', 
		'\n', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', '\x43', '\x2', 
		'\x2', '\x46', 'J', '\a', 'V', '\x2', '\x2', 'G', 'H', '\a', '\x63', '\x2', 
		'\x2', 'H', 'J', '\a', 'v', '\x2', '\x2', 'I', '\x45', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'G', '\x3', '\x2', '\x2', '\x2', 'J', '\f', '\x3', '\x2', 
		'\x2', '\x2', 'K', 'L', '\a', 'J', '\x2', '\x2', 'L', 'M', '\a', '\x43', 
		'\x2', '\x2', 'M', 'R', '\a', 'U', '\x2', '\x2', 'N', 'O', '\a', 'j', 
		'\x2', '\x2', 'O', 'P', '\a', '\x63', '\x2', '\x2', 'P', 'R', '\a', 'u', 
		'\x2', '\x2', 'Q', 'K', '\x3', '\x2', '\x2', '\x2', 'Q', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'R', '\xE', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', 
		'Y', '\x2', '\x2', 'T', 'U', '\a', 'K', '\x2', '\x2', 'U', 'V', '\a', 
		'V', '\x2', '\x2', 'V', '\\', '\a', 'J', '\x2', '\x2', 'W', 'X', '\a', 
		'y', '\x2', '\x2', 'X', 'Y', '\a', 'k', '\x2', '\x2', 'Y', 'Z', '\a', 
		'v', '\x2', '\x2', 'Z', '\\', '\a', 'j', '\x2', '\x2', '[', 'S', '\x3', 
		'\x2', '\x2', '\x2', '[', 'W', '\x3', '\x2', '\x2', '\x2', '\\', '\x10', 
		'\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '\x46', '\x2', '\x2', '^', 
		'_', '\a', 'G', '\x2', '\x2', '_', '`', '\a', 'H', '\x2', '\x2', '`', 
		'\x61', '\a', '\x43', '\x2', '\x2', '\x61', '\x62', '\a', 'W', '\x2', 
		'\x2', '\x62', '\x63', '\a', 'N', '\x2', '\x2', '\x63', 'l', '\a', 'V', 
		'\x2', '\x2', '\x64', '\x65', '\a', '\x66', '\x2', '\x2', '\x65', '\x66', 
		'\a', 'g', '\x2', '\x2', '\x66', 'g', '\a', 'h', '\x2', '\x2', 'g', 'h', 
		'\a', '\x63', '\x2', '\x2', 'h', 'i', '\a', 'w', '\x2', '\x2', 'i', 'j', 
		'\a', 'n', '\x2', '\x2', 'j', 'l', '\a', 'v', '\x2', '\x2', 'k', ']', 
		'\x3', '\x2', '\x2', '\x2', 'k', '\x64', '\x3', '\x2', '\x2', '\x2', 'l', 
		'\x12', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\a', '\x43', '\x2', '\x2', 
		'n', 'r', '\a', 'U', '\x2', '\x2', 'o', 'p', '\a', '\x63', '\x2', '\x2', 
		'p', 'r', '\a', 'u', '\x2', '\x2', 'q', 'm', '\x3', '\x2', '\x2', '\x2', 
		'q', 'o', '\x3', '\x2', '\x2', '\x2', 'r', '\x14', '\x3', '\x2', '\x2', 
		'\x2', 's', 't', '\a', 'H', '\x2', '\x2', 't', 'u', '\a', 'T', '\x2', 
		'\x2', 'u', 'v', '\a', 'Q', '\x2', '\x2', 'v', '|', '\a', 'O', '\x2', 
		'\x2', 'w', 'x', '\a', 'h', '\x2', '\x2', 'x', 'y', '\a', 't', '\x2', 
		'\x2', 'y', 'z', '\a', 'q', '\x2', '\x2', 'z', '|', '\a', 'o', '\x2', 
		'\x2', '{', 's', '\x3', '\x2', '\x2', '\x2', '{', 'w', '\x3', '\x2', '\x2', 
		'\x2', '|', '\x16', '\x3', '\x2', '\x2', '\x2', '}', '~', '\a', 'W', '\x2', 
		'\x2', '~', '\x7F', '\a', 'P', '\x2', '\x2', '\x7F', '\x80', '\a', 'K', 
		'\x2', '\x2', '\x80', '\x81', '\a', 'P', '\x2', '\x2', '\x81', '\x82', 
		'\a', 'U', '\x2', '\x2', '\x82', '\x83', '\a', 'V', '\x2', '\x2', '\x83', 
		'\x84', '\a', '\x43', '\x2', '\x2', '\x84', '\x85', '\a', 'N', '\x2', 
		'\x2', '\x85', '\x90', '\a', 'N', '\x2', '\x2', '\x86', '\x87', '\a', 
		'w', '\x2', '\x2', '\x87', '\x88', '\a', 'p', '\x2', '\x2', '\x88', '\x89', 
		'\a', 'k', '\x2', '\x2', '\x89', '\x8A', '\a', 'p', '\x2', '\x2', '\x8A', 
		'\x8B', '\a', 'u', '\x2', '\x2', '\x8B', '\x8C', '\a', 'v', '\x2', '\x2', 
		'\x8C', '\x8D', '\a', '\x63', '\x2', '\x2', '\x8D', '\x8E', '\a', 'n', 
		'\x2', '\x2', '\x8E', '\x90', '\a', 'n', '\x2', '\x2', '\x8F', '}', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x86', '\x3', '\x2', '\x2', '\x2', '\x90', 
		'\x18', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\a', 'G', '\x2', 
		'\x2', '\x92', '\x93', '\a', 'Z', '\x2', '\x2', '\x93', '\x94', '\a', 
		'G', '\x2', '\x2', '\x94', '\x95', '\a', '\x45', '\x2', '\x2', '\x95', 
		'\x96', '\a', 'W', '\x2', '\x2', '\x96', '\x97', '\a', 'V', '\x2', '\x2', 
		'\x97', '\xA0', '\a', 'G', '\x2', '\x2', '\x98', '\x99', '\a', 'g', '\x2', 
		'\x2', '\x99', '\x9A', '\a', 'z', '\x2', '\x2', '\x9A', '\x9B', '\a', 
		'g', '\x2', '\x2', '\x9B', '\x9C', '\a', '\x65', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', 'w', '\x2', '\x2', '\x9D', '\x9E', '\a', 'v', '\x2', '\x2', 
		'\x9E', '\xA0', '\a', 'g', '\x2', '\x2', '\x9F', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '\x9F', '\x98', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\a', 'k', '\x2', '\x2', '\xA2', 
		'\xA3', '\a', 'p', '\x2', '\x2', '\xA3', '\xA4', '\a', 'u', '\x2', '\x2', 
		'\xA4', '\xA5', '\a', 'v', '\x2', '\x2', '\xA5', '\xA6', '\a', '\x63', 
		'\x2', '\x2', '\xA6', '\xA7', '\a', 'n', '\x2', '\x2', '\xA7', '\xA8', 
		'\a', 'n', '\x2', '\x2', '\xA8', '\xA9', '\a', '\x63', '\x2', '\x2', '\xA9', 
		'\xAA', '\a', 'v', '\x2', '\x2', '\xAA', '\xAB', '\a', 'k', '\x2', '\x2', 
		'\xAB', '\xAC', '\a', 'q', '\x2', '\x2', '\xAC', '\xAD', '\a', 'p', '\x2', 
		'\x2', '\xAD', '\xAE', '\a', '\x61', '\x2', '\x2', '\xAE', '\xAF', '\a', 
		'r', '\x2', '\x2', '\xAF', '\xB0', '\a', '\x63', '\x2', '\x2', '\xB0', 
		'\xB1', '\a', 't', '\x2', '\x2', '\xB1', '\xB2', '\a', '\x63', '\x2', 
		'\x2', '\xB2', '\xB3', '\a', 'o', '\x2', '\x2', '\xB3', '\xB4', '\a', 
		'g', '\x2', '\x2', '\xB4', '\xB5', '\a', 'v', '\x2', '\x2', '\xB5', '\xB6', 
		'\a', 'g', '\x2', '\x2', '\xB6', '\xB7', '\a', 't', '\x2', '\x2', '\xB7', 
		'\xB8', '\a', 'u', '\x2', '\x2', '\xB8', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\xB9', '\xBA', '\a', 'q', '\x2', '\x2', '\xBA', '\xBB', '\a', 
		'r', '\x2', '\x2', '\xBB', '\xBC', '\a', 'v', '\x2', '\x2', '\xBC', '\xBD', 
		'\a', 'k', '\x2', '\x2', '\xBD', '\xBE', '\a', 'q', '\x2', '\x2', '\xBE', 
		'\xBF', '\a', 'p', '\x2', '\x2', '\xBF', '\xC0', '\a', '\x63', '\x2', 
		'\x2', '\xC0', '\xC1', '\a', 'n', '\x2', '\x2', '\xC1', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', '\xC2', '\xC6', '\x5', '\x3', '\x2', '\x2', '\xC3', 
		'\xC6', '\x5', '\x5', '\x3', '\x2', '\xC4', '\xC6', '\x5', '\a', '\x4', 
		'\x2', '\xC5', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', 
		'\x2', '\x2', '\x2', '\xC5', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC6', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC5', '\x3', '\x2', '\x2', 
		'\x2', '\xC7', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xC8', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\xC9', '\xCD', '\a', '$', '\x2', '\x2', '\xCA', 
		'\xCC', '\v', '\x2', '\x2', '\x2', '\xCB', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\xCC', '\xCF', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCE', 
		'\xD0', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xCD', '\x3', '\x2', '\x2', 
		'\x2', '\xD0', '\xD1', '\a', '$', '\x2', '\x2', '\xD1', '\"', '\x3', '\x2', 
		'\x2', '\x2', '\xD2', '\xD3', '\a', '=', '\x2', '\x2', '\xD3', '$', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD5', '\a', '.', '\x2', '\x2', '\xD5', 
		'&', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\a', '*', '\x2', '\x2', 
		'\xD7', '(', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xD9', '\a', '+', '\x2', 
		'\x2', '\xD9', '*', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDB', '\a', 
		']', '\x2', '\x2', '\xDB', ',', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDD', 
		'\a', '_', '\x2', '\x2', '\xDD', '.', '\x3', '\x2', '\x2', '\x2', '\xDE', 
		'\xDF', '\a', '?', '\x2', '\x2', '\xDF', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xE0', '\xE2', '\t', '\x5', '\x2', '\x2', '\xE1', '\xE0', '\x3', 
		'\x2', '\x2', '\x2', '\xE2', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE3', 
		'\xE1', '\x3', '\x2', '\x2', '\x2', '\xE3', '\xE4', '\x3', '\x2', '\x2', 
		'\x2', '\xE4', '\xE5', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE6', '\b', 
		'\x19', '\x2', '\x2', '\xE6', '\x32', '\x3', '\x2', '\x2', '\x2', '\xE7', 
		'\xE9', '\a', '\xF', '\x2', '\x2', '\xE8', '\xE7', '\x3', '\x2', '\x2', 
		'\x2', '\xE8', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xEA', '\x3', 
		'\x2', '\x2', '\x2', '\xEA', '\xED', '\a', '\f', '\x2', '\x2', '\xEB', 
		'\xED', '\a', '\xF', '\x2', '\x2', '\xEC', '\xE8', '\x3', '\x2', '\x2', 
		'\x2', '\xEC', '\xEB', '\x3', '\x2', '\x2', '\x2', '\xED', '\xEE', '\x3', 
		'\x2', '\x2', '\x2', '\xEE', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xEE', 
		'\xEF', '\x3', '\x2', '\x2', '\x2', '\xEF', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\x13', '\x2', '\x43', 'I', 'Q', '[', 'k', 'q', '{', '\x8F', '\x9F', 
		'\xC5', '\xC7', '\xCD', '\xE3', '\xE8', '\xEC', '\xEE', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
