//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Botond\Documents\Siemens\Summer School\Final\AutoInstaller\AutoInstaller\AISL\AISL.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AISLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IAISLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] AISLParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.findInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFindInstruction([NotNull] AISLParser.FindInstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.hasBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHasBlock([NotNull] AISLParser.HasBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] AISLParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] AISLParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.nonChoiceParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonChoiceParameter([NotNull] AISLParser.NonChoiceParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.choiceParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChoiceParameter([NotNull] AISLParser.ChoiceParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.defaultOrFixed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultOrFixed([NotNull] AISLParser.DefaultOrFixedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.defaultParamValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultParamValue([NotNull] AISLParser.DefaultParamValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.fixedParamValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixedParamValue([NotNull] AISLParser.FixedParamValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.uninstallInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUninstallInstruction([NotNull] AISLParser.UninstallInstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.executeInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecuteInstruction([NotNull] AISLParser.ExecuteInstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.invokeInstallInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvokeInstallInstruction([NotNull] AISLParser.InvokeInstallInstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.invokeUninstallInstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvokeUninstallInstruction([NotNull] AISLParser.InvokeUninstallInstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.anything"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnything([NotNull] AISLParser.AnythingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.valueOrString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueOrString([NotNull] AISLParser.ValueOrStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AISLParser.optionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionList([NotNull] AISLParser.OptionListContext context);
}
